title: Awsome Flows
github_username: quincycheng
email: quincy.cheng@cyberark.com
theme: minima
description: A Collection of CyberArk Identity Flows by Quincy Cheng.


author:
  name: Quincy Cheng
  email: quincy.cheng@cyberark.com




plugins:
  - jekyll-feed
  - jekyll-remote-theme