title: Awsome Flows
github_username: quincycheng
email: quincy.cheng@cyberark.com
theme: minima
description: A Collection of CyberArk Identity Flows by Quincy Cheng.


name: Quincy Cheng




plugins:
  - jekyll-feed
  - jekyll-remote-theme